Metrics/LineLength:
  Max: 100

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Blocks:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingComma:
  Enabled: false
